/*
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.internal.api;

import io.openweb3.wallet.internal.ApiException;
import io.openweb3.wallet.models.CursorPageWebhookEvent;
import io.openweb3.wallet.models.Error;
import io.openweb3.wallet.models.ResendWebhookEventRequest;
import io.openweb3.wallet.models.ResendWebhookEventResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhookEventsApi
 */
@Ignore
public class WebhookEventsApiTest {

    private final WebhookEventsApi api = new WebhookEventsApi();

    
    /**
     * List webhook events
     *
     * List webhook events
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1WebhooksEventsListTest() throws ApiException {
        String cursor = null;
        List<String> eventType = null;
        Integer limit = null;
        CursorPageWebhookEvent response = api.v1WebhooksEventsList(cursor, eventType, limit);

        // TODO: test validations
    }
    
    /**
     * Resend webhook event
     *
     * Resend a webhook event to specific endpoint
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1WebhooksEventsResendTest() throws ApiException {
        ResendWebhookEventRequest resendWebhookEventRequest = null;
        ResendWebhookEventResponse response = api.v1WebhooksEventsResend(resendWebhookEventRequest);

        // TODO: test validations
    }
    
}
