/*
 * Wallet OpenAPI Documentation
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResendWebhookEventRequest struct for ResendWebhookEventRequest
type ResendWebhookEventRequest struct {
	// The endpoint id of the webhook event
	EndpointId string `json:"endpoint_id"`
	// The id of the webhook event
	EventId string `json:"event_id"`
}

// NewResendWebhookEventRequest instantiates a new ResendWebhookEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResendWebhookEventRequest(endpointId string, eventId string) *ResendWebhookEventRequest {
	this := ResendWebhookEventRequest{}
	this.EndpointId = endpointId
	this.EventId = eventId
	return &this
}

// NewResendWebhookEventRequestWithDefaults instantiates a new ResendWebhookEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResendWebhookEventRequestWithDefaults() *ResendWebhookEventRequest {
	this := ResendWebhookEventRequest{}
	return &this
}

// GetEndpointId returns the EndpointId field value
func (o *ResendWebhookEventRequest) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *ResendWebhookEventRequest) GetEndpointIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *ResendWebhookEventRequest) SetEndpointId(v string) {
	o.EndpointId = v
}

// GetEventId returns the EventId field value
func (o *ResendWebhookEventRequest) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *ResendWebhookEventRequest) GetEventIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *ResendWebhookEventRequest) SetEventId(v string) {
	o.EventId = v
}

func (o ResendWebhookEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["endpoint_id"] = o.EndpointId
	}
	if true {
		toSerialize["event_id"] = o.EventId
	}
	return json.Marshal(toSerialize)
}

type NullableResendWebhookEventRequest struct {
	value *ResendWebhookEventRequest
	isSet bool
}

func (v NullableResendWebhookEventRequest) Get() *ResendWebhookEventRequest {
	return v.value
}

func (v *NullableResendWebhookEventRequest) Set(val *ResendWebhookEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResendWebhookEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResendWebhookEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResendWebhookEventRequest(val *ResendWebhookEventRequest) *NullableResendWebhookEventRequest {
	return &NullableResendWebhookEventRequest{value: val, isSet: true}
}

func (v NullableResendWebhookEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResendWebhookEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


