/*
 * Wallet OpenAPI Documentations
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CursorPageApp struct for CursorPageApp
type CursorPageApp struct {
	HasNext *bool `json:"has_next,omitempty"`
	Items *[]App `json:"items,omitempty"`
	NextCursor *string `json:"next_cursor,omitempty"`
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

// NewCursorPageApp instantiates a new CursorPageApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPageApp() *CursorPageApp {
	this := CursorPageApp{}
	return &this
}

// NewCursorPageAppWithDefaults instantiates a new CursorPageApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPageAppWithDefaults() *CursorPageApp {
	this := CursorPageApp{}
	return &this
}

// GetHasNext returns the HasNext field value if set, zero value otherwise.
func (o *CursorPageApp) GetHasNext() bool {
	if o == nil || o.HasNext == nil {
		var ret bool
		return ret
	}
	return *o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageApp) GetHasNextOk() (*bool, bool) {
	if o == nil || o.HasNext == nil {
		return nil, false
	}
	return o.HasNext, true
}

// HasHasNext returns a boolean if a field has been set.
func (o *CursorPageApp) HasHasNext() bool {
	if o != nil && o.HasNext != nil {
		return true
	}

	return false
}

// SetHasNext gets a reference to the given bool and assigns it to the HasNext field.
func (o *CursorPageApp) SetHasNext(v bool) {
	o.HasNext = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CursorPageApp) GetItems() []App {
	if o == nil || o.Items == nil {
		var ret []App
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageApp) GetItemsOk() (*[]App, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CursorPageApp) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []App and assigns it to the Items field.
func (o *CursorPageApp) SetItems(v []App) {
	o.Items = &v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *CursorPageApp) GetNextCursor() string {
	if o == nil || o.NextCursor == nil {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageApp) GetNextCursorOk() (*string, bool) {
	if o == nil || o.NextCursor == nil {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CursorPageApp) HasNextCursor() bool {
	if o != nil && o.NextCursor != nil {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *CursorPageApp) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetPrevCursor returns the PrevCursor field value if set, zero value otherwise.
func (o *CursorPageApp) GetPrevCursor() string {
	if o == nil || o.PrevCursor == nil {
		var ret string
		return ret
	}
	return *o.PrevCursor
}

// GetPrevCursorOk returns a tuple with the PrevCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageApp) GetPrevCursorOk() (*string, bool) {
	if o == nil || o.PrevCursor == nil {
		return nil, false
	}
	return o.PrevCursor, true
}

// HasPrevCursor returns a boolean if a field has been set.
func (o *CursorPageApp) HasPrevCursor() bool {
	if o != nil && o.PrevCursor != nil {
		return true
	}

	return false
}

// SetPrevCursor gets a reference to the given string and assigns it to the PrevCursor field.
func (o *CursorPageApp) SetPrevCursor(v string) {
	o.PrevCursor = &v
}

func (o CursorPageApp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.HasNext != nil {
		toSerialize["has_next"] = o.HasNext
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.NextCursor != nil {
		toSerialize["next_cursor"] = o.NextCursor
	}
	if o.PrevCursor != nil {
		toSerialize["prev_cursor"] = o.PrevCursor
	}
	return json.Marshal(toSerialize)
}

type NullableCursorPageApp struct {
	value *CursorPageApp
	isSet bool
}

func (v NullableCursorPageApp) Get() *CursorPageApp {
	return v.value
}

func (v *NullableCursorPageApp) Set(val *CursorPageApp) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPageApp) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPageApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPageApp(val *CursorPageApp) *NullableCursorPageApp {
	return &NullableCursorPageApp{value: val, isSet: true}
}

func (v NullableCursorPageApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPageApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


