/*
 * Wallet OpenAPI Documentation
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Account struct for Account
type Account struct {
	// The current balance of the wallet
	Balance *string `json:"balance,omitempty"`
	// The currency associated with the wallet
	Currency *string `json:"currency,omitempty"`
	// Account id
	Id *string `json:"id,omitempty"`
	// The amount of the balance that is in transit
	InTransitBalance *string `json:"in_transit_balance,omitempty"`
	// The amount of the balance that is locked
	LockedBalance *string `json:"locked_balance,omitempty"`
	// The wallet's ID
	WalletId *string `json:"wallet_id,omitempty"`
}

// NewAccount instantiates a new Account object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccount() *Account {
	this := Account{}
	return &this
}

// NewAccountWithDefaults instantiates a new Account object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountWithDefaults() *Account {
	this := Account{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *Account) GetBalance() string {
	if o == nil || o.Balance == nil {
		var ret string
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetBalanceOk() (*string, bool) {
	if o == nil || o.Balance == nil {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *Account) HasBalance() bool {
	if o != nil && o.Balance != nil {
		return true
	}

	return false
}

// SetBalance gets a reference to the given string and assigns it to the Balance field.
func (o *Account) SetBalance(v string) {
	o.Balance = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Account) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Account) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Account) SetCurrency(v string) {
	o.Currency = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Account) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Account) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Account) SetId(v string) {
	o.Id = &v
}

// GetInTransitBalance returns the InTransitBalance field value if set, zero value otherwise.
func (o *Account) GetInTransitBalance() string {
	if o == nil || o.InTransitBalance == nil {
		var ret string
		return ret
	}
	return *o.InTransitBalance
}

// GetInTransitBalanceOk returns a tuple with the InTransitBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetInTransitBalanceOk() (*string, bool) {
	if o == nil || o.InTransitBalance == nil {
		return nil, false
	}
	return o.InTransitBalance, true
}

// HasInTransitBalance returns a boolean if a field has been set.
func (o *Account) HasInTransitBalance() bool {
	if o != nil && o.InTransitBalance != nil {
		return true
	}

	return false
}

// SetInTransitBalance gets a reference to the given string and assigns it to the InTransitBalance field.
func (o *Account) SetInTransitBalance(v string) {
	o.InTransitBalance = &v
}

// GetLockedBalance returns the LockedBalance field value if set, zero value otherwise.
func (o *Account) GetLockedBalance() string {
	if o == nil || o.LockedBalance == nil {
		var ret string
		return ret
	}
	return *o.LockedBalance
}

// GetLockedBalanceOk returns a tuple with the LockedBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetLockedBalanceOk() (*string, bool) {
	if o == nil || o.LockedBalance == nil {
		return nil, false
	}
	return o.LockedBalance, true
}

// HasLockedBalance returns a boolean if a field has been set.
func (o *Account) HasLockedBalance() bool {
	if o != nil && o.LockedBalance != nil {
		return true
	}

	return false
}

// SetLockedBalance gets a reference to the given string and assigns it to the LockedBalance field.
func (o *Account) SetLockedBalance(v string) {
	o.LockedBalance = &v
}

// GetWalletId returns the WalletId field value if set, zero value otherwise.
func (o *Account) GetWalletId() string {
	if o == nil || o.WalletId == nil {
		var ret string
		return ret
	}
	return *o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetWalletIdOk() (*string, bool) {
	if o == nil || o.WalletId == nil {
		return nil, false
	}
	return o.WalletId, true
}

// HasWalletId returns a boolean if a field has been set.
func (o *Account) HasWalletId() bool {
	if o != nil && o.WalletId != nil {
		return true
	}

	return false
}

// SetWalletId gets a reference to the given string and assigns it to the WalletId field.
func (o *Account) SetWalletId(v string) {
	o.WalletId = &v
}

func (o Account) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Balance != nil {
		toSerialize["balance"] = o.Balance
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.InTransitBalance != nil {
		toSerialize["in_transit_balance"] = o.InTransitBalance
	}
	if o.LockedBalance != nil {
		toSerialize["locked_balance"] = o.LockedBalance
	}
	if o.WalletId != nil {
		toSerialize["wallet_id"] = o.WalletId
	}
	return json.Marshal(toSerialize)
}

type NullableAccount struct {
	value *Account
	isSet bool
}

func (v NullableAccount) Get() *Account {
	return v.value
}

func (v *NullableAccount) Set(val *Account) {
	v.value = val
	v.isSet = true
}

func (v NullableAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccount(val *Account) *NullableAccount {
	return &NullableAccount{value: val, isSet: true}
}

func (v NullableAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


