/*
 * Wallet OpenAPI Documentation
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EstimateFeeRequest struct for EstimateFeeRequest
type EstimateFeeRequest struct {
	// The amount of currency to be withdrawn in nano units (multiply by 10^decimals)
	Amount string `json:"amount"`
	// The code of currency to be withdrawn.
	Currency string `json:"currency"`
	// The network of the currency to be withdrawn.
	Network string `json:"network"`
	// The recipient address where the withdrawn funds will be sent. This is usually a wallet address specific to the chosen network.
	ToAddress string `json:"to_address"`
	// The ID of the wallet from which the withdrawal will be made.
	WalletId string `json:"wallet_id"`
}

// NewEstimateFeeRequest instantiates a new EstimateFeeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateFeeRequest(amount string, currency string, network string, toAddress string, walletId string) *EstimateFeeRequest {
	this := EstimateFeeRequest{}
	this.Amount = amount
	this.Currency = currency
	this.Network = network
	this.ToAddress = toAddress
	this.WalletId = walletId
	return &this
}

// NewEstimateFeeRequestWithDefaults instantiates a new EstimateFeeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateFeeRequestWithDefaults() *EstimateFeeRequest {
	this := EstimateFeeRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *EstimateFeeRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *EstimateFeeRequest) SetAmount(v string) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *EstimateFeeRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *EstimateFeeRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetNetwork returns the Network field value
func (o *EstimateFeeRequest) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetNetworkOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *EstimateFeeRequest) SetNetwork(v string) {
	o.Network = v
}

// GetToAddress returns the ToAddress field value
func (o *EstimateFeeRequest) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetToAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *EstimateFeeRequest) SetToAddress(v string) {
	o.ToAddress = v
}

// GetWalletId returns the WalletId field value
func (o *EstimateFeeRequest) GetWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value
// and a boolean to check if the value has been set.
func (o *EstimateFeeRequest) GetWalletIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WalletId, true
}

// SetWalletId sets field value
func (o *EstimateFeeRequest) SetWalletId(v string) {
	o.WalletId = v
}

func (o EstimateFeeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if true {
		toSerialize["network"] = o.Network
	}
	if true {
		toSerialize["to_address"] = o.ToAddress
	}
	if true {
		toSerialize["wallet_id"] = o.WalletId
	}
	return json.Marshal(toSerialize)
}

type NullableEstimateFeeRequest struct {
	value *EstimateFeeRequest
	isSet bool
}

func (v NullableEstimateFeeRequest) Get() *EstimateFeeRequest {
	return v.value
}

func (v *NullableEstimateFeeRequest) Set(val *EstimateFeeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateFeeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateFeeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateFeeRequest(val *EstimateFeeRequest) *NullableEstimateFeeRequest {
	return &NullableEstimateFeeRequest{value: val, isSet: true}
}

func (v NullableEstimateFeeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateFeeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


