/*
 * Wallet OpenAPI Documentation
 *
 * This is a custody wallet service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PageWallet struct for PageWallet
type PageWallet struct {
	Items []Wallet `json:"items"`
	Total int32 `json:"total"`
}

// NewPageWallet instantiates a new PageWallet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageWallet(items []Wallet, total int32) *PageWallet {
	this := PageWallet{}
	this.Items = items
	this.Total = total
	return &this
}

// NewPageWalletWithDefaults instantiates a new PageWallet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageWalletWithDefaults() *PageWallet {
	this := PageWallet{}
	return &this
}

// GetItems returns the Items field value
func (o *PageWallet) GetItems() []Wallet {
	if o == nil {
		var ret []Wallet
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PageWallet) GetItemsOk() (*[]Wallet, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *PageWallet) SetItems(v []Wallet) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *PageWallet) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PageWallet) GetTotalOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PageWallet) SetTotal(v int32) {
	o.Total = v
}

func (o PageWallet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullablePageWallet struct {
	value *PageWallet
	isSet bool
}

func (v NullablePageWallet) Get() *PageWallet {
	return v.value
}

func (v *NullablePageWallet) Set(val *PageWallet) {
	v.value = val
	v.isSet = true
}

func (v NullablePageWallet) IsSet() bool {
	return v.isSet
}

func (v *NullablePageWallet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageWallet(val *PageWallet) *NullablePageWallet {
	return &NullablePageWallet{value: val, isSet: true}
}

func (v NullablePageWallet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageWallet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


