/*
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.wallet.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateGasStationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-04T08:51:30.487331+08:00[Asia/Shanghai]")
public class CreateGasStationRequest {
  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  private Boolean disabled;

  public static final String SERIALIZED_NAME_GAS_CAPACITY = "gas_capacity";
  @SerializedName(SERIALIZED_NAME_GAS_CAPACITY)
  private String gasCapacity;

  public static final String SERIALIZED_NAME_GAS_THRESHOLD = "gas_threshold";
  @SerializedName(SERIALIZED_NAME_GAS_THRESHOLD)
  private String gasThreshold;

  public static final String SERIALIZED_NAME_MAX_FEE_LIMIT = "max_fee_limit";
  @SerializedName(SERIALIZED_NAME_MAX_FEE_LIMIT)
  private String maxFeeLimit;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private String network;


  public CreateGasStationRequest disabled(Boolean disabled) {
    
    this.disabled = disabled;
    return this;
  }

   /**
   * Disabled
   * @return disabled
  **/
  @ApiModelProperty(required = true, value = "Disabled")

  public Boolean getDisabled() {
    return disabled;
  }


  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


  public CreateGasStationRequest gasCapacity(String gasCapacity) {
    
    this.gasCapacity = gasCapacity;
    return this;
  }

   /**
   * Gas Capacity
   * @return gasCapacity
  **/
  @ApiModelProperty(required = true, value = "Gas Capacity")

  public String getGasCapacity() {
    return gasCapacity;
  }


  public void setGasCapacity(String gasCapacity) {
    this.gasCapacity = gasCapacity;
  }


  public CreateGasStationRequest gasThreshold(String gasThreshold) {
    
    this.gasThreshold = gasThreshold;
    return this;
  }

   /**
   * Gas Threshold
   * @return gasThreshold
  **/
  @ApiModelProperty(required = true, value = "Gas Threshold")

  public String getGasThreshold() {
    return gasThreshold;
  }


  public void setGasThreshold(String gasThreshold) {
    this.gasThreshold = gasThreshold;
  }


  public CreateGasStationRequest maxFeeLimit(String maxFeeLimit) {
    
    this.maxFeeLimit = maxFeeLimit;
    return this;
  }

   /**
   * Max Fee Limit
   * @return maxFeeLimit
  **/
  @ApiModelProperty(required = true, value = "Max Fee Limit")

  public String getMaxFeeLimit() {
    return maxFeeLimit;
  }


  public void setMaxFeeLimit(String maxFeeLimit) {
    this.maxFeeLimit = maxFeeLimit;
  }


  public CreateGasStationRequest network(String network) {
    
    this.network = network;
    return this;
  }

   /**
   * Network
   * @return network
  **/
  @ApiModelProperty(required = true, value = "Network")

  public String getNetwork() {
    return network;
  }


  public void setNetwork(String network) {
    this.network = network;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateGasStationRequest createGasStationRequest = (CreateGasStationRequest) o;
    return Objects.equals(this.disabled, createGasStationRequest.disabled) &&
        Objects.equals(this.gasCapacity, createGasStationRequest.gasCapacity) &&
        Objects.equals(this.gasThreshold, createGasStationRequest.gasThreshold) &&
        Objects.equals(this.maxFeeLimit, createGasStationRequest.maxFeeLimit) &&
        Objects.equals(this.network, createGasStationRequest.network);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disabled, gasCapacity, gasThreshold, maxFeeLimit, network);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateGasStationRequest {\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    gasCapacity: ").append(toIndentedString(gasCapacity)).append("\n");
    sb.append("    gasThreshold: ").append(toIndentedString(gasThreshold)).append("\n");
    sb.append("    maxFeeLimit: ").append(toIndentedString(maxFeeLimit)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

