/**
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyNetwork } from './CurrencyNetwork';
import { HttpFile } from '../http/http';

export class Currency {
    /**
    * Is it depositable on-chain
    */
    'canDeposit': boolean;
    /**
    * Is it transferable within the platform
    */
    'canTransfer': boolean;
    /**
    * Is it withdrawable on-chain
    */
    'canWithdraw': boolean;
    /**
    * Currency code identifier
    */
    'code': string;
    /**
    * Contract address (for token contracts, if applicable)
    */
    'contractAddress'?: string;
    /**
    * Decimal precision
    */
    'decimals': number;
    /**
    * Indicates if the currency is disabled
    */
    'disabled': boolean;
    /**
    * Currency logo URL
    */
    'logo': string;
    /**
    * Maximum fee
    */
    'maxFee': string;
    /**
    * Maximum fee for contract addresses
    */
    'maxFeeForCtAddr': string;
    /**
    * Maximum withdraw amount per transaction in nano units (multiply by 10^decimals)
    */
    'maxWithdrawAmount': string;
    /**
    * Minimum deposit amount per transaction in nano units (multiply by 10^decimals)
    */
    'minDepositAmount': string;
    /**
    * Minimum fee
    */
    'minFee': string;
    /**
    * Minimum fee for contract addresses
    */
    'minFeeForCtAddr': string;
    /**
    * Minimum transfer amount per transaction in nano units (multiply by 10^decimals)
    */
    'minTransferAmount': string;
    /**
    * Minimum withdraw amount per transaction in nano units (multiply by 10^decimals)
    */
    'minWithdrawAmount': string;
    /**
    * Currency name
    */
    'name': string;
    /**
    * Does it require a memo/note for transactions
    */
    'needMemo': boolean;
    /**
    * Networks information
    */
    'networks': Array<CurrencyNetwork>;
    /**
    * The number of decimals used by the currency
    */
    'precision': number;
    /**
    * Participate in exchange rate calculation
    */
    'rated': boolean;
    /**
    * Currency symbol
    */
    'symbol': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "canDeposit",
            "baseName": "can_deposit",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canTransfer",
            "baseName": "can_transfer",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWithdraw",
            "baseName": "can_withdraw",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractAddress",
            "baseName": "contract_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "decimals",
            "baseName": "decimals",
            "type": "number",
            "format": ""
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxFee",
            "baseName": "max_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxFeeForCtAddr",
            "baseName": "max_fee_for_ct_addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxWithdrawAmount",
            "baseName": "max_withdraw_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "minDepositAmount",
            "baseName": "min_deposit_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "minFee",
            "baseName": "min_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "minFeeForCtAddr",
            "baseName": "min_fee_for_ct_addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "minTransferAmount",
            "baseName": "min_transfer_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "minWithdrawAmount",
            "baseName": "min_withdraw_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "needMemo",
            "baseName": "need_memo",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "networks",
            "baseName": "networks",
            "type": "Array<CurrencyNetwork>",
            "format": ""
        },
        {
            "name": "precision",
            "baseName": "precision",
            "type": "number",
            "format": ""
        },
        {
            "name": "rated",
            "baseName": "rated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Currency.attributeTypeMap;
    }
    
    public constructor() {
    }
}

