/**
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EstimateFeeResponse {
    'feeAmount': string;
    'feeCurrency': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "feeAmount",
            "baseName": "fee_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "feeCurrency",
            "baseName": "fee_currency",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EstimateFeeResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

