/**
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EstimateResponse {
    /**
    * The amount of the base currency you want to convert
    */
    'baseAmount': string;
    /**
    * The currency code of the base currency that you want to convert from
    */
    'baseCurrency': string;
    /**
    * The exchange rate from the base currency to the target currency
    */
    'rate': number;
    /**
    * The amount of the target currency you will receive after the conversion
    */
    'toAmount': string;
    /**
    * The currency code of the target currency that you want to convert to
    */
    'toCurrency': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "baseAmount",
            "baseName": "base_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "baseCurrency",
            "baseName": "base_currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "toAmount",
            "baseName": "to_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "toCurrency",
            "baseName": "to_currency",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EstimateResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

