/**
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExchangeSubmitResponse {
    /**
    * The exchange id
    */
    'exchangeId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "exchangeId",
            "baseName": "exchange_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExchangeSubmitResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

