/**
 * Wallet OpenAPI Documentation
 * This is a custody wallet service openapi server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExchangeCurrencyPairs {
    /**
    * The currency code of source currency, e.g.: TON
    */
    'fromCurrency'?: string;
    /**
    * The currency code list of target currency, e.g.: USDT
    */
    'toCurrencies'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromCurrency",
            "baseName": "from_currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "toCurrencies",
            "baseName": "to_currencies",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExchangeCurrencyPairs.attributeTypeMap;
    }
    
    public constructor() {
    }
}

